// shell/layer_surface.cpp
// Wayland layer-shell surface implementation
#include "layer_surface.h"

#include <straylight/log.h>

#include <wayland-client.h>

// The wlr-layer-shell protocol header is generated by wayland-scanner
// at build time. We forward-declare the types we need here and use
// the generated bindings via function pointers at runtime.
struct zwlr_layer_shell_v1;
struct zwlr_layer_surface_v1;

// Layer-shell protocol function declarations (from generated header)
extern "C" {
struct zwlr_layer_surface_v1* zwlr_layer_shell_v1_get_layer_surface(
    struct zwlr_layer_shell_v1* layer_shell,
    struct wl_surface* surface,
    struct wl_output* output,
    uint32_t layer,
    const char* ns);

void zwlr_layer_surface_v1_set_size(
    struct zwlr_layer_surface_v1* layer_surface,
    uint32_t width, uint32_t height);

void zwlr_layer_surface_v1_set_anchor(
    struct zwlr_layer_surface_v1* layer_surface,
    uint32_t anchor);

void zwlr_layer_surface_v1_set_exclusive_zone(
    struct zwlr_layer_surface_v1* layer_surface,
    int32_t zone);

void zwlr_layer_surface_v1_ack_configure(
    struct zwlr_layer_surface_v1* layer_surface,
    uint32_t serial);

void zwlr_layer_surface_v1_destroy(
    struct zwlr_layer_surface_v1* layer_surface);

int zwlr_layer_surface_v1_add_listener(
    struct zwlr_layer_surface_v1* layer_surface,
    const void* listener, void* data);
}

namespace straylight::shell {

struct LayerSurface::Impl {
    wl_display*    display      = nullptr;
    wl_compositor* compositor   = nullptr;
    wl_surface*    wl_surf      = nullptr;
    zwlr_layer_shell_v1*   layer_shell   = nullptr;
    zwlr_layer_surface_v1* layer_surface = nullptr;

    int  width_          = 0;
    int  height_         = 0;
    int  exclusive_zone_ = 0;
    bool configured_     = false;

    ~Impl() {
        destroy();
    }

    void destroy() {
        if (layer_surface) {
            zwlr_layer_surface_v1_destroy(layer_surface);
            layer_surface = nullptr;
        }
        if (wl_surf) {
            wl_surface_destroy(wl_surf);
            wl_surf = nullptr;
        }
    }
};

// Layer-shell configure callback: compositor tells us the final size
static void layer_surface_configure(void* data, void* /*surface*/,
                                    uint32_t serial,
                                    uint32_t width, uint32_t height) {
    auto* impl = static_cast<LayerSurface::Impl*>(data);
    if (width > 0)  impl->width_  = static_cast<int>(width);
    if (height > 0) impl->height_ = static_cast<int>(height);
    impl->configured_ = true;

    zwlr_layer_surface_v1_ack_configure(impl->layer_surface, serial);
    wl_surface_commit(impl->wl_surf);

    SL_DEBUG("Layer surface configured: {}x{}", impl->width_, impl->height_);
}

// Layer-shell closed callback
static void layer_surface_closed(void* data, void* /*surface*/) {
    auto* impl = static_cast<LayerSurface::Impl*>(data);
    SL_INFO("Layer surface closed by compositor");
    impl->destroy();
}

// Listener struct layout must match zwlr_layer_surface_v1_listener
struct LayerSurfaceListener {
    void (*configure)(void*, void*, uint32_t, uint32_t, uint32_t);
    void (*closed)(void*, void*);
};

static const LayerSurfaceListener layer_listener = {
    .configure = layer_surface_configure,
    .closed    = layer_surface_closed,
};

LayerSurface::LayerSurface(std::unique_ptr<Impl> impl)
    : impl_(std::move(impl)) {}

LayerSurface::~LayerSurface() = default;
LayerSurface::LayerSurface(LayerSurface&& other) noexcept = default;
LayerSurface& LayerSurface::operator=(LayerSurface&& other) noexcept = default;

Result<LayerSurface, SLError> LayerSurface::create(
    wl_display* display,
    wl_compositor* compositor,
    void* layer_shell_raw,
    Layer layer,
    Anchor anchor,
    int width,
    int height,
    int exclusive_zone) {

    if (!display || !compositor || !layer_shell_raw) {
        return Result<LayerSurface, SLError>::error(
            SLError{SLErrorCode::InvalidArgument,
                    "Null Wayland display, compositor, or layer_shell"});
    }

    auto impl = std::make_unique<Impl>();
    impl->display      = display;
    impl->compositor   = compositor;
    impl->layer_shell  = static_cast<zwlr_layer_shell_v1*>(layer_shell_raw);
    impl->width_       = width;
    impl->height_      = height;
    impl->exclusive_zone_ = exclusive_zone;

    // Create wl_surface
    impl->wl_surf = wl_compositor_create_surface(compositor);
    if (!impl->wl_surf) {
        return Result<LayerSurface, SLError>::error(
            SLError{SLErrorCode::NotInitialized,
                    "Failed to create wl_surface"});
    }

    // Create layer surface
    impl->layer_surface = zwlr_layer_shell_v1_get_layer_surface(
        impl->layer_shell,
        impl->wl_surf,
        nullptr,  // null output = default
        static_cast<uint32_t>(layer),
        "straylight-shell");

    if (!impl->layer_surface) {
        return Result<LayerSurface, SLError>::error(
            SLError{SLErrorCode::NotInitialized,
                    "Failed to create layer surface"});
    }

    // Configure the layer surface
    zwlr_layer_surface_v1_set_size(impl->layer_surface,
                                   static_cast<uint32_t>(width),
                                   static_cast<uint32_t>(height));
    zwlr_layer_surface_v1_set_anchor(impl->layer_surface,
                                     static_cast<uint32_t>(anchor));

    if (exclusive_zone > 0) {
        zwlr_layer_surface_v1_set_exclusive_zone(impl->layer_surface,
                                                  exclusive_zone);
    }

    // Attach listener
    zwlr_layer_surface_v1_add_listener(
        impl->layer_surface, &layer_listener, impl.get());

    // Initial commit to trigger configure event
    wl_surface_commit(impl->wl_surf);
    wl_display_roundtrip(display);

    SL_INFO("Layer surface created: {}x{}, layer={}, exclusive_zone={}",
            width, height, static_cast<uint32_t>(layer), exclusive_zone);

    return Result<LayerSurface, SLError>::ok(
        LayerSurface(std::move(impl)));
}

wl_surface* LayerSurface::surface() const {
    return impl_ ? impl_->wl_surf : nullptr;
}

int LayerSurface::width() const {
    return impl_ ? impl_->width_ : 0;
}

int LayerSurface::height() const {
    return impl_ ? impl_->height_ : 0;
}

bool LayerSurface::configured() const {
    return impl_ ? impl_->configured_ : false;
}

void LayerSurface::destroy() {
    if (impl_) {
        impl_->destroy();
    }
}

} // namespace straylight::shell
