#!/bin/bash
set -e

lb config noauto \
    --architectures amd64 \
    --distribution bookworm \
    --archive-areas "main contrib non-free non-free-firmware" \
    --binary-images iso-hybrid \
    --binary-filesystem ext4 \
    --debian-installer none \
    --bootloaders grub-efi \
    --bootappend-live "boot=live components quiet splash" \
    --iso-application "StrayLight OS" \
    --iso-publisher "StrayLight OS Team <dev@straylight.dev>" \
    --iso-volume "StrayLight OS 1.0.0" \
    --image-name "straylight-os-1.0.0-amd64" \
    --debootstrap-options "--variant=minbase" \
    --apt-recommends true \
    --security true \
    --updates true \
    --backports false \
    --cache true \
    --cache-packages true \
    --firmware-binary true \
    --firmware-chroot true \
    --memtest none \
    --win32-loader false \
    --checksums sha256 \
    "${@}"
